import functions

print("ВАРИАНТ 2")
print("ЗАДАНИЕ 1")
a = int(input("Введите а "))
b = int(input("Введите b "))
print("Результат:", *functions.f1(a, b))
print()
print("ЗАДАНИЕ 2")
functions.f2(1, 2, 3, 4, 5, 6)
print()
print("ЗАДАНИЕ 3")
print("Наименьшее значение ключевых элементов",functions.f3())
print()
print("ЗАДАНИЕ 4")
print("Числа, куб которыx больше 17:", *functions.f4([1, 2, 3, 4, 7, 10, 12]))
print()
print("ЗАДАНИЕ 5")
print("Функция: вычисление квадрата числа")
functions.square_of_nums(1, 2, 3, 4, 5, 6)